apply plugin: 'com.android.application'

android {
    namespace 'com.saad.autocaption'
    compileSdk 34

    defaultConfig {
        applicationId "com.saad.autocaption"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'net.java.dev.jna:jna:5.13.0@aar'
    implementation 'com.alphacephei:vosk-android:0.3.47'
    implementation 'com.moizhassan.ffmpeg:ffmpeg-kit-16kb:6.1.1'
}
